# Integración de datasets

En este notebook se integran los datasets limpios de canciones (`songs_clean.csv`) y artistas (`artists_clean.csv`) mediante la función `merge_songs_artists()` definida en `src/soporte_merge.py`.

El objetivo es construir un único dataset analítico que permita estudiar conjuntamente las características de las canciones y de sus artistas.

Durante este proceso se realizan las siguientes tareas:

- Carga de los datasets limpios.
- Conversión de la columna `artist_ids` en listas de Python.
- Expansión de las colaboraciones mediante `explode()`, generando una fila por artista.
- Unión de ambos datasets mediante el identificador del artista.
- Renombrado de columnas para mejorar la interpretación.
- Creación de variables auxiliares para el análisis.
- Validación del resultado del merge.
- Gestión de valores nulos.
- Exportación del dataset final.

In [26]:
# ============================
# 1. Importaciones
# ============================
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

import sys
sys.path.append("../")

from src import soporte_merge as spm

In [27]:
# ============================
# 2. Carga de datos
# ============================
songs = pd.read_csv("../data/processed/songs_clean.csv")
artists = pd.read_csv("../data/processed/artists_clean.csv")

In [28]:
# ============================
# 3. Integracióon de Datasets
# ============================
music = spm.merge_songs_artists(
    songs,
    artists
)

## Validación del merge

Una vez integrados ambos datasets, se realiza una validación inicial para comprobar que el proceso de unión se ha realizado correctamente y que el conjunto de datos resultante mantiene la calidad esperada.

En esta fase se revisan:

- Las dimensiones del dataset resultante.
- Los tipos de datos de cada variable.
- La existencia de valores nulos tras la integración.
- La presencia de registros duplicados considerando la combinación **song_id + artist_id**, ya que una misma canción puede estar asociada a varios artistas tras la expansión de colaboraciones.
- El número de canciones cuyo identificador de artista no encuentra correspondencia en el dataset de artistas.

Estas comprobaciones permiten detectar posibles inconsistencias antes de gestionar los valores nulos y generar el dataset final para el análisis exploratorio.

In [29]:
# ============================
# 4. Validación del Merge
# ============================

print("Dimensiones del dataset:")
print(music.shape)

print("\nTipos de datos:")
display(music.dtypes)

print("\nValores nulos:")
display(
    music.isna()
         .sum()
         .sort_values(ascending=False)
)

print("\nDuplicados (song_id + artist_id):")
print(
    music.duplicated(
        subset=["song_id", "artist_id"]
    ).sum()
)

print("\nCanciones sin artista asociado:")
print(
    music["artist_name"].isna().sum()
)

display(music.head())

Dimensiones del dataset:
(679269, 38)

Tipos de datos:

song_id                                 str
song_name                               str
album_name                              str
artists                                 str
danceability                        float64
energy                              float64
key                                   int64
loudness                            float64
mode                                    str
speechiness                         float64
acousticness                        float64
instrumentalness                    float64
liveness                            float64
valence                             float64
tempo                               float64
duration_ms                           int64
year                                  int64
genre                                   str
song_popularity                       int64
total_artist_followers                int64
avg_artist_popularity               float64
niche_genres                            str
n_artists                             int64
main_artist                             str
n_niche_genres                        int64
decade                                  str
popularity_per_million_followers    float64
song_duration_min                   float64
artist_id                               str
artist_name                             str
artist_followers                      int64
artist_popularity                     int64
artist_genres                           str
main_genre                              str
n_genres                              int64
is_collaboration                       bool
artist_has_genres                      bool
artist_followers_millions           float64
dtype: object

Valores nulos:

album_name                          127
artist_name                          96
song_name                            44
popularity_per_million_followers     18
main_artist                           7
song_id                               0
energy                                0
danceability                          0
artists                               0
key                                   0
acousticness                          0
loudness                              0
mode                                  0
speechiness                           0
tempo                                 0
duration_ms                           0
year                                  0
genre                                 0
song_popularity                       0
instrumentalness                      0
liveness                              0
valence                               0
niche_genres                          0
avg_artist_popularity                 0
total_artist_followers                0
n_artists                             0
decade                                0
n_niche_genres                        0
song_duration_min                     0
artist_id                             0
artist_followers                      0
artist_popularity                     0
artist_genres                         0
main_genre                            0
n_genres                              0
is_collaboration                      0
artist_has_genres                     0
artist_followers_millions             0
dtype: int64

Duplicados (song_id + artist_id):
0

Canciones sin artista asociado:
96

,song_id,song_name,album_name,artists,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,year,genre,song_popularity,total_artist_followers,avg_artist_popularity,niche_genres,n_artists,main_artist,n_niche_genres,decade,popularity_per_million_followers,song_duration_min,artist_id,artist_name,artist_followers,artist_popularity,artist_genres,main_genre,n_genres,is_collaboration,artist_has_genres,artist_followers_millions
0,0prct5tdjanegiqbxcldy9,NaN,undenable,['hellyeah'],0.415,0.605,7,-11.157,major,0.0575,0.001160,0.838000,0.471,0.193,100.059,79500,2016,rock,0,769490,52.0,"['groove metal', 'metal']",1,hellyeah,2,2010s,0.00,1.32,4hxdvvq5t8ebpypdbl1f9f,hellyeah,769490,52,"['groove metal', 'metal']",rock,2,False,True,0.77
1,2asl4wirkeym3owzxxkyuq,NaN,childhood dreams,['yxngxr1'],0.788,0.648,7,-9.135,minor,0.3150,0.900000,0.000000,0.176,0.287,79.998,114000,2019,hip-hop,29,143628,45.0,[],1,yxngxr1,0,2010s,201.91,1.90,2jwrhcdgkrhelyemqnddke,yxngxr1,143628,45,[],hip-hop,0,False,False,0.14
2,5ta3imw310llko8embj2ga,noble stabbings,situationist comedy,['dillinger four'],0.171,0.957,2,-5.749,major,0.1490,0.000029,0.000032,0.330,0.349,175.317,197400,2002,rock,0,36619,35.0,"['melodic hardcore', 'pop punk', 'punk', 'skat...",1,dillinger four,4,2000s,0.00,3.29,4yan46l70qv0pgxlmg0ihi,dillinger four,36619,35,"['punk', 'skate punk', 'melodic hardcore', 'po...",rock,4,False,True,0.04
3,0frot4kk5otm8xo8px6ejf,i'll be back,i'll be back,['rilès'],0.823,0.612,1,-7.767,major,0.2480,0.168000,0.000000,0.109,0.688,142.959,178533,2018,hip-hop,43,929303,63.0,['french rap'],1,rilès,1,2010s,46.27,2.98,6pdcqa7by8ikuovxvgknli,rilès,929303,63,['french rap'],hip-hop,1,False,True,0.93
4,1xbfhv5faebv3mmwxx7dns,lost,lost,['rilès'],0.729,0.552,7,-8.562,minor,0.0650,0.183000,0.000000,0.131,0.380,86.103,186197,2018,hip-hop,0,929303,63.0,['french rap'],1,rilès,1,2010s,0.00,3.10,6pdcqa7by8ikuovxvgknli,rilès,929303,63,['french rap'],hip-hop,1,False,True,0.93

In [30]:
# ============================
# 5. Revisión de nuevas variables
# ============================
display(
    music[
        [
            "song_name",
            "artist_name",
            "song_popularity",
            "artist_popularity",
            "artist_followers",
            "artist_followers_millions",
            "is_collaboration",
            "artist_has_genres"
        ]
    ].head()
)

,song_name,artist_name,song_popularity,artist_popularity,artist_followers,artist_followers_millions,is_collaboration,artist_has_genres
0,NaN,hellyeah,0,52,769490,0.77,False,True
1,NaN,yxngxr1,29,45,143628,0.14,False,False
2,noble stabbings,dillinger four,0,35,36619,0.04,False,True
3,i'll be back,rilès,43,63,929303,0.93,False,True
4,lost,rilès,0,63,929303,0.93,False,True

## Gestión de valores nulos

Tras realizar el merge se revisan los valores nulos presentes en el dataset para decidir si deben conservarse o eliminarse.

No todos los valores nulos representan errores. En algunos casos corresponden a información que no está disponible en el dataset original y conservarlos resulta más apropiado que imputar valores artificiales.

Se adopta el siguiente criterio:

- **song_name:** se eliminan los registros sin nombre de canción, ya que impiden identificar correctamente el elemento analizado.

- **artist_name:** se eliminan los registros cuyo identificador de artista no existe en el dataset de artistas. Estos casos representan inconsistencias entre ambos conjuntos de datos y no permiten realizar análisis sobre el artista.

- **album_name:** se conservan los valores nulos, ya que algunas canciones corresponden a sencillos o el álbum no está informado en la fuente original.

- **main_artist:** se conservan los valores nulos porque proceden de listas vacías en el dataset original y no afectan al análisis al disponer igualmente del nombre del artista tras la integración.

- **popularity_per_million_followers:** se conservan los valores nulos porque la métrica no puede calcularse cuando el artista no dispone de seguidores registrados.

In [31]:
# ============================
# 6. Gestión de Valores Nulos
# ============================
music = music.dropna(
    subset=["song_name", "artist_name"]
)

In [32]:
# ============================
# 7. Validación Final
# ============================
print("Dimensiones finales:")
print(music.shape)

print("\nValores nulos restantes:")
display(
    music.isna().sum().sort_values(ascending=False)
)

print("\nDuplicados por canción y artista:")
print(
    music.duplicated(
        subset=["song_id", "artist_id"]
    ).sum()
)

display(music.head())

Dimensiones finales:
(679129, 38)

Valores nulos restantes:

album_name                          125
popularity_per_million_followers     18
main_artist                           6
artists                               0
song_name                             0
song_id                               0
energy                                0
danceability                          0
key                                   0
loudness                              0
acousticness                          0
instrumentalness                      0
mode                                  0
speechiness                           0
tempo                                 0
duration_ms                           0
year                                  0
genre                                 0
song_popularity                       0
total_artist_followers                0
liveness                              0
valence                               0
niche_genres                          0
avg_artist_popularity                 0
n_niche_genres                        0
n_artists                             0
decade                                0
song_duration_min                     0
artist_id                             0
artist_name                           0
artist_followers                      0
artist_popularity                     0
artist_genres                         0
main_genre                            0
n_genres                              0
is_collaboration                      0
artist_has_genres                     0
artist_followers_millions             0
dtype: int64

Duplicados por canción y artista:
0

,song_id,song_name,album_name,artists,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,year,genre,song_popularity,total_artist_followers,avg_artist_popularity,niche_genres,n_artists,main_artist,n_niche_genres,decade,popularity_per_million_followers,song_duration_min,artist_id,artist_name,artist_followers,artist_popularity,artist_genres,main_genre,n_genres,is_collaboration,artist_has_genres,artist_followers_millions
2,5ta3imw310llko8embj2ga,noble stabbings,situationist comedy,['dillinger four'],0.171,0.957,2,-5.749,major,0.1490,0.000029,0.000032,0.330,0.349,175.317,197400,2002,rock,0,36619,35.0,"['melodic hardcore', 'pop punk', 'punk', 'skat...",1,dillinger four,4,2000s,0.00,3.29,4yan46l70qv0pgxlmg0ihi,dillinger four,36619,35,"['punk', 'skate punk', 'melodic hardcore', 'po...",rock,4,False,True,0.04
3,0frot4kk5otm8xo8px6ejf,i'll be back,i'll be back,['rilès'],0.823,0.612,1,-7.767,major,0.2480,0.168000,0.000000,0.109,0.688,142.959,178533,2018,hip-hop,43,929303,63.0,['french rap'],1,rilès,1,2010s,46.27,2.98,6pdcqa7by8ikuovxvgknli,rilès,929303,63,['french rap'],hip-hop,1,False,True,0.93
4,1xbfhv5faebv3mmwxx7dns,lost,lost,['rilès'],0.729,0.552,7,-8.562,minor,0.0650,0.183000,0.000000,0.131,0.380,86.103,186197,2018,hip-hop,0,929303,63.0,['french rap'],1,rilès,1,2010s,0.00,3.10,6pdcqa7by8ikuovxvgknli,rilès,929303,63,['french rap'],hip-hop,1,False,True,0.93
5,0gnntocw3qjabgtybsjt3h,que vida - mono version,da capo deluxe edition,['love'],0.600,0.540,9,-11.803,major,0.0328,0.525000,0.003050,0.100,0.547,125.898,220560,1966,rock,20,273598,46.0,"['acid rock', 'baroque pop', 'proto-punk', 'ps...",1,love,4,1960s,73.10,3.68,3q6ookfssqomsttl11j5uk,love,273598,46,"['psychedelic rock', 'baroque pop', 'acid rock...",rock,4,False,True,0.27
6,1scfa6gt3r6julsiqpdwy3,liaf cipe,the bree-teenz,['one morning left'],0.483,0.894,9,-4.164,major,0.0546,0.000027,0.003940,0.374,0.284,140.058,200200,2011,rock,0,38169,34.0,"['metalcore', 'post-hardcore']",1,one morning left,2,2010s,0.00,3.34,4qgkwf55nqfgytozkozprf,one morning left,38169,34,"['metalcore', 'post-hardcore']",rock,2,False,True,0.04

In [33]:
# ============================
# 8. Guuardar Dataset
# ============================
music.to_csv(
    "../data/processed/music_dataset.csv",
    index=False
)